# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/Dataloading-Copy4.ipynb (unless otherwise specified).

__all__ = []

# Cell
import pandas as pd
from pathlib import Path
import json
from functools import partial
from PIL import Image
import numpy as np
from itertools import chain
from fast.torch_basics import *
from fast.layers import *
from fast.data.all import *
from fast.data.block import *
from fast.optimizer import *
from fast.learner import *
from fast.metrics import *
from fast.callback.all import *
from fast.vision.all import *
from anime.ugatit import *
from fast.callback.wandb import WandbCallback
from anime.kid import *
import wandb
from fast.fp16_utils import convert_module
#from fast.callback.tensorboard import TensorBoardCallback

# Cell
import pandas as pd
from pathlib import Path
import json
from functools import partial
from PIL import Image
import numpy as np
from itertools import chain
from fastai2.torch_basics import *
from fastai2.layers import *
from fastai2.data.all import *
from fastai2.data.block import *
from fastai2.optimizer import *
from fastai2.learner import *
from fastai2.metrics import *
from fastai2.callback.all import *
from fastai2.vision.all import *
from anime.ugatit import *
from fastai2.callback.wandb import WandbCallback
import wandb
from fastai2.fp16_utils import convert_module
from anime.ugatit_networks import ILN,adaILN
from fastai2.callback.fp16 import _copy_state
from torch.autograd import Variable
import gc
import math

# Cell
import pandas as pd
from pathlib import Path
import json
from functools import partial
from PIL import Image
import numpy as np
from itertools import chain
from fastai2.torch_basics import *
from fastai2.layers import *
from fastai2.data.all import *
from fastai2.data.block import *
from fastai2.optimizer import *
from fastai2.learner import *
from fastai2.metrics import *
from fastai2.callback.all import *
from fastai2.vision.all import *
from anime.ugatit import *
from fastai2.callback.wandb import WandbCallback
import wandb
from fastai2.fp16_utils import convert_module
from anime.ugatit_networks import ILN,adaILN
from fastai2.callback.fp16 import _copy_state
from torch.autograd import Variable
from anime.callbacks import *
import gc
import math

# Cell
import pandas as pd
from pathlib import Path
import json
from functools import partial
from PIL import Image
import numpy as np
from itertools import chain
from fastai2.torch_basics import *
from fastai2.layers import *
from fastai2.data.all import *
from fastai2.data.block import *
from fastai2.optimizer import *
from fastai2.learner import *
from fastai2.metrics import *
from fastai2.callback.all import *
from fastai2.vision.all import *
from anime.ugatit import *
from fastai2.callback.wandb import WandbCallback
import wandb
from fastai2.fp16_utils import convert_module
from anime.ugatit_networks import ILN,adaILN
from fastai2.callback.fp16 import _copy_state
from torch.autograd import Variable
from anime.callbacks import *
import gc
import math

# Cell
import pandas as pd
from pathlib import Path
import json
from functools import partial
from PIL import Image
import numpy as np
from itertools import chain
from fast.torch_basics import *
from fast.layers import *
from fast.data.all import *
from fast.data.block import *
from fast.optimizer import *
from fast.learner import *
from fast.metrics import *
from fast.callback.all import *
from fast.vision.all import *
from anime.ugatit import *
from fast.callback.wandb import WandbCallback
from anime.kid import *
import wandb
#from fast.callback.tensorboard import TensorBoardCallback

# Cell
import pandas as pd
from pathlib import Path
import json
from functools import partial
from PIL import Image
import numpy as np
from itertools import chain
from local.torch_basics import *
from local.test import *
from local.layers import *
from local.data.all import *
from local.data.block import *
from local.optimizer import *
from local.learner import *
from local.metrics import *
from local.callback.all import *
from local.vision.all import *

# Cell
import pandas as pd
from pathlib import Path
import json
from functools import partial
from PIL import Image
import numpy as np
from itertools import chain
from fastai2.torch_basics import *
from fastai2.layers import *
from fastai2.data.all import *
from fastai2.data.block import *
from fastai2.optimizer import *
from fastai2.learner import *
from fastai2.metrics import *
from fastai2.callback.all import *
from fastai2.vision.all import *
from anime.ugatit import *
from fastai2.callback.wandb import WandbCallback
import wandb
from fastai2.fp16_utils import convert_module
from anime.ugatit_networks import ILN,adaILN
from fastai2.callback.fp16 import _copy_state
from torch.autograd import Variable
import gc
import math