# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://marii.github.io/selfie2anime/"

git_url = "https://github.com/marii/selfie2anime/tree/master/"

def custom_doc_links(name): return None
