# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GANOptimizer": "Callbacks.ipynb",
         "Switch": "Callbacks.ipynb",
         "LinearDecreaseLR": "Callbacks.ipynb",
         "SameXbYb": "Callbacks.ipynb",
         "CachedMemoryDebug": "Callbacks.ipynb",
         "OptimizedOptimizer": "Callbacks.ipynb",
         "zero_grad": "Callbacks.ipynb",
         "zero_Adam": "Callbacks.ipynb",
         "clear_grads": "Callbacks.ipynb",
         "MetricRecorder": "Callbacks.ipynb",
         "Conditional_Loss": "Callbacks.ipynb",
         "convert_module_alt": "Callbacks.ipynb",
         "convert_network": "Callbacks.ipynb",
         "GAN_splitter": "Callbacks.ipynb",
         "GANWandb": "Callbacks.ipynb",
         "get_master": "Callbacks.ipynb",
         "clear_to_master_grads": "Callbacks.ipynb",
         "ModelToHalfAdaLIN": "Callbacks.ipynb",
         "MixedPrecisionTuple": "Callbacks.ipynb",
         "Perf": "Callbacks.ipynb",
         "MixedPrecisionTupleNo32": "Callbacks.ipynb",
         "SaveModelCallback": "Callbacks.ipynb",
         "DSList": "Dataloading-Split.ipynb",
         "denorm": "Dataloading-Split.ipynb",
         "CycleImage": "Dataloading-Split.ipynb",
         "CyclePair": "Dataloading-Split.ipynb",
         "ToTensorTuple": "Dataloading-Split.ipynb",
         "resized_image": "Dataloading-Split.ipynb",
         "ListofTransformsforTuple": "Dataloading-Split.ipynb",
         "NoopTensor": "Dataloading-Split.ipynb",
         "UGATITData": "Dataloading-Split.ipynb",
         "Inception_v3": "Kernel Inception Distance.ipynb",
         "KernelInceptionDistanceMetric": "Kernel Inception Distance.ipynb",
         "KIDCallback": "Kernel Inception Distance.ipynb",
         "KernelInceptionDistance": "Kernel Inception Distance.ipynb",
         "fakemodule": "UGATIT_Original.ipynb",
         "UGATIT": "UGATIT.ipynb",
         "UgatitModel": "UGATIT.ipynb",
         "UGATITLoss": "UGATIT.ipynb",
         "MixedPrecision_LayerNorm": "UGATIT-networks.ipynb",
         "ResnetBlock": "UGATIT-networks.ipynb",
         "Spliter": "UGATIT-networks.ipynb",
         "ResnetGenerator": "UGATIT-networks.ipynb",
         "ResnetAdaILNBlock": "UGATIT-networks.ipynb",
         "adaILN": "UGATIT-networks.ipynb",
         "ILN": "UGATIT-networks.ipynb",
         "Discriminator": "UGATIT-networks.ipynb",
         "RhoClipper": "UGATIT-networks.ipynb",
         "path": "UGATIT_Original.ipynb"}

modules = ["anime/callbacks.py",
           "anime/oudataloader.py",
           "anime/dataloader.py",
           "anime/dataloading.py",
           "anime/kid.py",
           "anime/ugatit.py",
           "anime/ugatit_networks.py",
           "anime/ugatit_original.py"]

doc_url = "https://marii.github.io/selfie2anime/"

git_url = "https://github.com/marii/selfie2anime/tree/master/"

def custom_doc_links(name): return None
